Repository jacob-alford/schemata-ts, pull requests merged in 2022-09, with the labels that each got.

#24 Add string module: ASCII
  src/Decoder.ts
  src/Eq.ts
  src/Guard.ts
  src/SchemableExt.ts
  src/TaskDecoder.ts
  src/Type.ts
  src/string/ASCII.ts
  tests/ASCII.test.ts
  tests/EmailAddress.test.ts
Labels: string

#25 Regenerate documentation and add instructions to README
  README.md
  docs/index.md
  docs/modules/date/SafeDate.ts.md
  docs/modules/number/Int.ts.md
  docs/modules/number/Natural.ts.md
  docs/modules/number/NegativeInt.ts.md
  docs/modules/number/PositiveInt.ts.md
  docs/modules/string/ASCII.ts.md
  docs/modules/string/EmailAddress.ts.md
  docs/modules/string/ISODateString.ts.md
  docs/modules/string/IntString.ts.md
  docs/modules/string/NaturalString.ts.md
  docs/modules/string/NegativeIntString.ts.md
  docs/modules/string/NonemptyString.ts.md
  docs/modules/string/PositiveIntString.ts.md
  docs/modules/string/UUID.ts.md
Labels: documentation

#32 Replace `master` with `main`
  .github/workflows/build.yml
  README.md
Labels: build

#33 Add links in docs
  docs/modules/string/ASCII.ts.md
  docs/modules/string/UUID.ts.md
  src/string/ASCII.ts
  src/string/UUID.ts
Labels: documentation

#82 [#73] Add module header JSDoc comments to SchemableExt methods
  scripts/schemableGen.ts
  src/SchemableExt.ts
Labels: enhancement
